version: '3.8'

services:
  mcp-speech-to-text:
    build:
      context: .
      dockerfile: Dockerfile
    image: mcp-speech-to-text:v1.0.0
    container_name: mcp-stt-server
    ports:
      - "8000:8000"
    environment:
      - WHISPER_MODEL_SIZE=base
      - DEFAULT_LANGUAGE=auto
      - LOG_LEVEL=INFO
    volumes:
      # Mount directory for audio files
      - ./audio:/app/audio:ro
      # Mount directory for output
      - ./output:/app/output
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: mcp-stt-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - mcp-speech-to-text
    restart: unless-stopped
    profiles:
      - production

volumes:
  audio_data:
  output_data:
